---
- name: install docker
  hosts: all
  become: yes

  tasks:

  - name: Remove docker if installed
    yum:
     name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
     state: removed
 
  - name: Install yum utils
    yum:
     name: yum-utils
     state: latest

  - name: add repo
    get_url:
     url: https://download.docker.com/linux/centos/docker-ce.repo
     dest: /etc/yum.repos.d/docer-ce.repo
    become: yes

  - name: Install Docker
    package:
     name: docker-ce
     state: latest
    become: yes

  - name: Start Docker service
    service:
     name: docker
     state: started
     enabled: yes
    become: yes

  - name: Add user vagrant to docker group
    user:
     name: vagrant
     groups: docker
     append: yes
    become: yes
